# Generated by Django 5.2.8 on 2025-11-30 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'cargos',
            },
        ),
        migrations.CreateModel(
            name='Fleet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20, unique=True)),
                ('model', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('в эксплуатации', 'В эксплуатации'), ('на ремонте', 'На ремонте'), ('простой', 'Простой')], max_length=50)),
                ('capacity', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'fleet',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'clients',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('patronymic', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('driving_license', models.CharField(max_length=50)),
                ('experience_years', models.IntegerField()),
                ('status', models.CharField(choices=[('свободен', 'Свободен'), ('в пути', 'В пути'), ('на простое', 'На простое')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('fleet', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='transport.fleet')),
            ],
            options={
                'db_table': 'drivers',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('оформлен', 'Оформлен'), ('в пути', 'В пути'), ('доставлен', 'Доставлен'), ('отменён', 'Отменён')], max_length=50)),
                ('delivery_type', models.CharField(choices=[('локальная', 'Локальная'), ('междугородняя', 'Междугородняя')], max_length=50)),
                ('requested_drivers_count', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='transport.cargo')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='transport.client')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.driver')),
            ],
            options={
                'db_table': 'delivery',
            },
        ),
        migrations.CreateModel(
            name='DriverDowntime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('total_duration', models.DurationField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.driver')),
            ],
            options={
                'db_table': 'driver_downtime',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='transport.client')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='transport.delivery')),
            ],
            options={
                'db_table': 'feedbacks',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(choices=[('карта', 'Карта'), ('наличные', 'Наличные')], max_length=50)),
                ('status', models.CharField(choices=[('проведён', 'Проведён'), ('отклонён', 'Отклонён'), ('в обработке', 'В обработке'), ('возврат', 'Возврат')], max_length=50)),
                ('comment', models.TextField(blank=True, null=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='transport.delivery')),
            ],
            options={
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_city', models.CharField(max_length=100)),
                ('departure_street', models.CharField(max_length=100)),
                ('departure_house', models.CharField(max_length=20)),
                ('arrival_city', models.CharField(max_length=100)),
                ('arrival_street', models.CharField(max_length=100)),
                ('arrival_house', models.CharField(max_length=20)),
                ('distance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estimated_time', models.DurationField(blank=True, null=True)),
                ('delivery', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='transport.delivery')),
            ],
            options={
                'db_table': 'routes',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('водитель', 'Водитель'), ('клиент', 'Клиент'), ('администратор', 'Администратор')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='VehicleMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('запланировано', 'Запланировано'), ('в процессе', 'В процессе'), ('завершено', 'Завершено'), ('отменено', 'Отменено')], max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('fleet', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='transport.fleet')),
            ],
            options={
                'db_table': 'vehicle_maintenance',
            },
        ),
    ]
