# Generated by Django 5.2.8 on 2025-12-20 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_alter_driver_fleet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleet',
            name='status',
            field=models.CharField(choices=[('используется', 'Используется'), ('на стоянке', 'На стоянке')], default='на стоянке', max_length=50),
        ),
    ]
