# Generated by Django 5.2.8 on 2025-12-20 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_alter_fleet_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='requested_drivers_count',
        ),
    ]
