# Generated by Django 5.2.8 on 2025-12-20 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_remove_delivery_requested_drivers_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DriverDowntime',
        ),
    ]
