# Generated by Django 5.2.8 on 2025-12-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0005_delete_driverdowntime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='comment',
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('проведён', 'Проведён'), ('отклонён', 'Отклонён')], max_length=50),
        ),
    ]
