# Generated by Django 5.2.8 on 2025-12-20 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0006_remove_payment_comment_alter_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='status',
        ),
    ]
