# Generated by Django 5.2.8 on 2025-12-20 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0007_remove_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='estimated_time',
        ),
    ]
