# Generated by Django 5.2.8 on 2025-12-20 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0008_remove_route_estimated_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='first_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='last_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='patronymic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
