# Generated by Django 5.2.8 on 2025-12-21 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0009_client_first_name_client_last_name_client_patronymic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refueling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата заправки')),
                ('fuel_type', models.CharField(choices=[('АИ-92', 'АИ-92'), ('АИ-95', 'АИ-95'), ('ДТ', 'Дизель'), ('Газ', 'Газ')], max_length=20, verbose_name='Вид топлива')),
                ('liters', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Литры')),
                ('cost_per_liter', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена за литр')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Общая стоимость')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.driver', verbose_name='Водитель')),
                ('fleet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.fleet', verbose_name='Автомобиль')),
            ],
            options={
                'verbose_name': 'Заправка',
                'verbose_name_plural': 'Заправки',
                'db_table': 'refueling',
            },
        ),
    ]
