# Generated by Django 5.2.8 on 2025-12-21 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0010_refueling'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VehicleMaintenance',
        ),
    ]
